version: '2'

services:
  data:
    build: ./yacs-prereq-data
    expose:
      - "3100"
    ports:
      - "3100:3100"
    volumes:
      - ./yacs-prereq-data/src:/usr/src/app/src
    command: "ruby app.rb"
    
  web:
    build: ./yacs-prereq-web
    ports:
      - "4200:4200"
    volumes:
      - ./yacs-prereq-web/src:/usr/src/app/src
    depends_on:
      - data
    command: "npm start"
